name: Deploy Validity Check Lambda
on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        description: "S3 bucket name for storing Terraform plans"
        required: true
      s3_path:
        description: "S3 path prefix for plans "
        required: true

jobs:
  terraform:
    name: 'Deploy Validity Check  Lambda'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Deploy Lambda
      - name: Deploy Validity Check  Lambda
        working-directory: IaC/Lambda/Validity_Check/ValidityCheck-starter
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan-lambda-ValidityCheck-starter
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 cp tfplan-lambda-ValidityCheck-starter s3://${{ github.event.inputs.s3_bucket }}/${{ github.event.inputs.s3_path }}/tfplan-lambda-ValidityCheck-starter-${TIMESTAMP}
          terraform apply -auto-approve tfplan-lambda-ValidityCheck-starter

      - name: Deploy Validity Check  Lambda
        working-directory: IaC/Lambda/Validity_Check/ValidityCheck-worker
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan-lambda-ValidityCheck-worker
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 cp tfplan-lambda-ValidityCheck-worker s3://${{ github.event.inputs.s3_bucket }}/${{ github.event.inputs.s3_path }}/tfplan-lambda-ValidityCheck-worker-${TIMESTAMP}
          terraform apply -auto-approve tfplan-lambda-ValidityCheck-worker

      - name: Deploy Validity Check  Lambda
        working-directory: IaC/Lambda/Validity_Check/ValidityCheck-collector
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan-lambda-ValidityCheck-collector
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 cp tfplan-lambda-ValidityCheck-collector s3://${{ github.event.inputs.s3_bucket }}/${{ github.event.inputs.s3_path }}/tfplan-lambda-ValidityCheck-collector-${TIMESTAMP}
          terraform apply -auto-approve tfplan-lambda-ValidityCheck-collector